# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ZambeelSniper.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from selenium_test import *
import os

zambeel_logo_file_path = os.path.dirname(__file__) + "\\Zambeel.jpg"



class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(973, 592)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.roll_number_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.roll_number_edit.setGeometry(QtCore.QRect(70, 100, 271, 51))
        self.roll_number_edit.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(26, 70, 157);")
        self.roll_number_edit.setObjectName("roll_number_edit")
        self.password_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.password_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_edit.setGeometry(QtCore.QRect(70, 190, 271, 51))
        self.password_edit.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(26, 70, 157);")
        self.password_edit.setObjectName("password_edit")
        self.zambeel_logo = QtWidgets.QLabel(self.centralwidget)
        self.zambeel_logo.setGeometry(QtCore.QRect(790, 30, 131, 131))
        self.zambeel_logo.setPixmap(QtGui.QPixmap(zambeel_logo_file_path))
        self.zambeel_logo.setScaledContents(True)
        self.zambeel_logo.setObjectName("zambeel_logo")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(720, 460, 201, 71))
        self.pushButton.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\"; color: rgb(61, 135, 255) ; ")
        self.pushButton.setObjectName("pushButton")
        self.course_selection_box = QtWidgets.QComboBox(self.centralwidget)
        self.course_selection_box.setGeometry(QtCore.QRect(70, 320, 371, 51))
        self.course_selection_box.setStyleSheet("color: rgb(35, 123, 255);\n"
"font: 10pt \"Lucida Fax\";")
        self.course_selection_box.setObjectName("course_selection_box")
        self.course_selection_box.addItem("")
        self.course_selection_box.addItem("")
        self.course_selection_box.addItem("")
        self.course_selection_box.addItem("")
        self.course_selection_box.addItem("")
        self.roll_number_label = QtWidgets.QLabel(self.centralwidget)
        self.roll_number_label.setGeometry(QtCore.QRect(70, 80, 131, 16))
        self.roll_number_label.setObjectName("roll_number_label")
        self.password_label = QtWidgets.QLabel(self.centralwidget)
        self.password_label.setGeometry(QtCore.QRect(70, 170, 131, 16))
        self.password_label.setObjectName("password_label")
        self.select_coure = QtWidgets.QLabel(self.centralwidget)
        self.select_coure.setGeometry(QtCore.QRect(70, 300, 131, 16))
        self.select_coure.setObjectName("select_coure")
        self.work_in_progress = QtWidgets.QLabel(self.centralwidget)
        self.work_in_progress.setGeometry(QtCore.QRect(670, 310, 271, 51))
        self.work_in_progress.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 82, 200);")
        self.work_in_progress.setObjectName("work_in_progress")
        self.developed_by = QtWidgets.QLabel(self.centralwidget)
        self.developed_by.setGeometry(QtCore.QRect(20, 520, 211, 16))
        self.developed_by.setObjectName("developed_by")
        self.ZS_logo_1 = QtWidgets.QLabel(self.centralwidget)
        self.ZS_logo_1.setGeometry(QtCore.QRect(10, -20, 141, 81))
        self.ZS_logo_1.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(26, 70, 157);")
        self.ZS_logo_1.setObjectName("ZS_logo_1")
        self.ZS_logo_2 = QtWidgets.QLabel(self.centralwidget)
        self.ZS_logo_2.setGeometry(QtCore.QRect(70, 10, 121, 81))
        self.ZS_logo_2.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(231, 182, 5);")
        self.ZS_logo_2.setObjectName("ZS_logo_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 973, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton.clicked.connect(lambda: self.enroll(self.roll_number_edit.text(),self.password_edit.text()))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "ENROLL"))
        self.course_selection_box.setItemText(0, _translate("MainWindow", "CS 334-S1 (1107)"))
        self.course_selection_box.setItemText(1, _translate("MainWindow", "CS 340-S2 (1110)"))
        self.course_selection_box.setItemText(2, _translate("MainWindow", "CS 370-S2 (1112)"))
        self.course_selection_box.setItemText(3, _translate("MainWindow", "CS 466-S1 (1603)"))
        self.course_selection_box.setItemText(4, _translate("MainWindow", "MGMT 212-S1 (1433)"))
        self.roll_number_label.setText(_translate("MainWindow", "Roll Number"))
        self.password_label.setText(_translate("MainWindow", "Password"))
        self.select_coure.setText(_translate("MainWindow", "Select Course"))
        self.work_in_progress.setText(_translate("MainWindow", "Work Still In Progress"))
        self.developed_by.setText(_translate("MainWindow", "Developed by: Neebi20"))
        self.ZS_logo_1.setText(_translate("MainWindow", "ZAMBEEL"))
        self.ZS_logo_2.setText(_translate("MainWindow", "SNIPER"))

    def enroll(self,id,pswd):
        call_chrome(id,pswd)

        
    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
