# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ZS_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from selenium_test import *
import os
zambeel_logo_file_path = os.path.dirname(__file__) + "\\Zambeel.jpg"




class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1065, 708)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.rollNumber_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.rollNumber_lineEdit.setGeometry(QtCore.QRect(80, 130, 261, 41))
        self.rollNumber_lineEdit.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.rollNumber_lineEdit.setObjectName("rollNumber_lineEdit")
        self.password_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.password_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineEdit.setGeometry(QtCore.QRect(80, 220, 261, 41))
        self.password_lineEdit.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.Zambeel_logo = QtWidgets.QLabel(self.centralwidget)
        self.Zambeel_logo.setGeometry(QtCore.QRect(900, 20, 141, 131))
        self.Zambeel_logo.setText("")
        self.Zambeel_logo.setPixmap(QtGui.QPixmap(zambeel_logo_file_path))
        self.Zambeel_logo.setScaledContents(True)
        self.Zambeel_logo.setObjectName("Zambeel_logo")
        self.rollNumber_description = QtWidgets.QLabel(self.centralwidget)
        self.rollNumber_description.setGeometry(QtCore.QRect(80, 110, 81, 16))
        self.rollNumber_description.setObjectName("rollNumber_description")
        self.pswd_description = QtWidgets.QLabel(self.centralwidget)
        self.pswd_description.setGeometry(QtCore.QRect(80, 200, 55, 16))
        self.pswd_description.setObjectName("pswd_description")
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setGeometry(QtCore.QRect(900, 600, 141, 51))
        self.stopButton.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 12pt \"Arial\";")
        self.stopButton.setObjectName("stopButton")
        self.enrollButton = QtWidgets.QPushButton(self.centralwidget)
        self.enrollButton.setGeometry(QtCore.QRect(900, 540, 141, 51))
        self.enrollButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.enrollButton.setMouseTracking(False)
        self.enrollButton.setStyleSheet("color:rgb(26, 70, 157);\n"
"font: 12pt \"Arial\";\n"
"")
        self.enrollButton.setAutoDefault(False)
        self.enrollButton.setDefault(True)
        self.enrollButton.setObjectName("enrollButton")
        self.Instructions_description = QtWidgets.QLabel(self.centralwidget)
        self.Instructions_description.setGeometry(QtCore.QRect(20, 390, 151, 51))
        self.Instructions_description.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.Instructions_description.setObjectName("Instructions_description")
        self.InstructionsBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.InstructionsBrowser.setGeometry(QtCore.QRect(20, 440, 661, 211))
        self.InstructionsBrowser.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.InstructionsBrowser.setObjectName("InstructionsBrowser")
        self.Z_logo = QtWidgets.QLabel(self.centralwidget)
        self.Z_logo.setGeometry(QtCore.QRect(20, 10, 181, 51))
        self.Z_logo.setStyleSheet("color: rgb(26, 70, 157);\n"
"font: 22pt \"MS Shell Dlg 2\";")
        self.Z_logo.setObjectName("Z_logo")
        self.S_logo = QtWidgets.QLabel(self.centralwidget)
        self.S_logo.setGeometry(QtCore.QRect(90, 40, 181, 51))
        self.S_logo.setStyleSheet("color: rgb(229, 215, 13);\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.S_logo.setObjectName("S_logo")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(80, 310, 341, 41))
        self.comboBox.setStyleSheet("color:rgb(25, 122, 147);\n"
"font: 10pt \"Microsoft Sans Serif\";")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.developed_by = QtWidgets.QLabel(self.centralwidget)
        self.developed_by.setGeometry(QtCore.QRect(90, 80, 141, 16))
        self.developed_by.setStyleSheet("font: 75 6pt \"MS Shell Dlg 2\";\n"
"")
        self.developed_by.setObjectName("developed_by")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1065, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.enrollButton.clicked.connect(lambda: self.enroll(self.rollNumber_lineEdit.text(),self.password_lineEdit.text()))
        self.stopButton.clicked.connect(self.stop)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.rollNumber_description.setText(_translate("MainWindow", "Roll Number"))
        self.pswd_description.setText(_translate("MainWindow", "Password"))
        self.stopButton.setText(_translate("MainWindow", "STOP"))
        self.enrollButton.setText(_translate("MainWindow", "ENROLL"))
        self.Instructions_description.setText(_translate("MainWindow", "INSTRUCTIONS:"))
        self.InstructionsBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Hi! Welcome to Zambeel Sniper(ZS)!<br /><br />Are you tired of not getting your desired courses?</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Did someone steal your course while you were swapping?<br />Did you spend your whole day on your Laptop during the Add/Drop Period, hoping you might get the course?</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Did someone else get the course even after you saw it &quot;Open&quot; for a moment?<br />Worry not! ZS is here to save you time and effort!<br /><br />Please follow these instructions carefully for this application to work properly:<br />1. Please add your desired course to your shopping cart beforehand.<br />2. Select the course in the list provided.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">3. Press Enroll and see the magic happen.<br /><br />This App is only compatible with Windows Devices (Windows 10 or later).<br />For queries and complaints, feel free to email at neebitwenty@gmail.com </span></p></body></html>"))
        self.Z_logo.setText(_translate("MainWindow", "ZAMBEEL"))
        self.S_logo.setText(_translate("MainWindow", "SNIPER"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Default"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Course A"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Course B"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Course C"))
        self.developed_by.setText(_translate("MainWindow", "Developed by: Neebi20"))

    def enroll(self,id,pswd):  
        call_chrome(id,pswd)

    def stop(self):
        exit()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setWindowIcon(QtGui.QIcon(os.path.dirname(__file__) + "\\Zambeel.ico"))
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
